RoRService/RoRService/Controllers/GameBoardController.cs
using RoRService.Engines.Contracts;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RoRService.Controllers
{
    public class GameBoardController : Controller
    {
        readonly string _gameCookieName = "GAME_COOKIE";

        IGameEngine gameEngine;

        public GameBoardController(IGameEngine gameEngine)
        {
            this.gameEngine = gameEngine;
        }

        public ActionResult Index()
        {
            var gameCookie = Request.Cookies.Get(_gameCookieName);

            if (gameCookie != null)
            {
                return RedirectToAction("ResumeGame", new { gameId = gameCookie.Value});
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> ResumeGame(long gameId)
        {
            var gameBoardVM = await gameEngine.ResumeGame(gameId);

            return View(gameBoardVM);
        }

        public async Task<ActionResult> StartGame(long gameId)
        {
            await gameEngine.StartGame(gameId);

            return RedirectToAction("ResumeGame", new { gameId = gameId});
        }
    }
}

RoRService/RoRService/Controllers/GameLobbyController.cs
using AutoMapper;
using RoRService.Helpers;
using RoRService.Models.DataModels;
using RoRService.Models.ViewModels.PlayersViewModels;
using RoRService.Models.ViewModels.GamesViewModels;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RoRService.Resources.Contracts;
using System.Collections.Generic;
using RoRService.Models.DataModels.Enums;

namespace RoRService.Controllers
{
    [Authorize]
    public class GameLobbyController : Controller
    {
        IGamesResource gamesResource;
        IPlayersResource playersResource;

        public GameLobbyController(IGamesResource gamesResource, IPlayersResource playersResource)
        {
            this.gamesResource = gamesResource;
            this.playersResource = playersResource;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "The Republic of Rome";
            return View();
        }

        public async Task<ActionResult> GetGameList(string checkedOptions)
        {
            var checkedOptionList = HttpUtility.ParseQueryString(checkedOptions);
            var gameList = await gamesResource.GetGameList();

            var config = new MapperConfiguration(cfg => { cfg.CreateMap<Game, GameListVM>(); });
            var iMapper = config.CreateMapper();
            var gameListVM = iMapper.Map<List<Game>, List<GameListVM>>(gameList);

            return PartialView("_gameList",
                               gameListVM.Where(g => (g.Status != GameStatus.Open || checkedOptionList["openGames"] != null) &&
                                                     (g.Status != GameStatus.Playing || checkedOptionList["playingGames"] != null) &&
                                                     (g.Status != GameStatus.Completed || checkedOptionList["completedGames"] != null))
                                         .OrderByDescending(g => g.DateOfLastAction)
                                           
                              );
        }

        public async Task<ActionResult> GetMyGameList(string playerName, string checkedOptions)
        {
            var checkedOptionList = HttpUtility.ParseQueryString(checkedOptions);
            var gameList = await gamesResource.GetGameList();

            var config = new MapperConfiguration(cfg => { cfg.CreateMap<Game, GameListVM>(); });
            var iMapper = config.CreateMapper();
            var gameListVM = iMapper.Map<List<Game>, List<GameListVM>>(gameList);

            return PartialView("_gameList",
                                   gameListVM.Where(g => (g.Owner == playerName) &&
                                                         (g.Status != GameStatus.Open || checkedOptionList["openGames"] != null) &&
                                                         (g.Status != GameStatus.Playing || checkedOptionList["playingGames"] != null) &&
                                                         (g.Status != GameStatus.Completed || checkedOptionList["completedGames"] != null))
                                             .OrderByDescending(g => g.DateOfLastAction)
                                  );
        }

        public async Task<ActionResult> GetGameDetails(long id)
        {
            var game = await gamesResource.GetGameDetails(id);

            var config = new MapperConfiguration(cfg => { cfg.CreateMap<Game, GameDetailsVM>(); });
            var iMapper = config.CreateMapper();
            var gameDetailVM = iMapper.Map<Game, GameDetailsVM>(game);

            return PartialView("_gameDetails", gameDetailVM);
        }

        public async Task<ActionResult> AddPlayerToGame(GameDetailsVM gameDetailsVM)
        {
            if (gameDetailsVM.PlayerList.Count > 5)
            {
                ModelState.AddModelError("CustomError", "Cannot have more than 6 Players in a game");
            }

            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg => { cfg.CreateMap<NewPlayerVM, Player>(); });
                var iMapper = config.CreateMapper();
                var newPlayer = iMapper.Map<NewPlayerVM, Player>(gameDetailsVM.NewPlayer);

                var response = await playersResource.AddPlayerToGame(gameDetailsVM.Id, newPlayer);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetGameDetails", new { id = gameDetailsVM.Id });
                }
                else
                {
                    ModelState.AddModelError("CustomError", response.ToString());
                    return PartialView("_gameDetails", gameDetailsVM);
                }
            }
            else
            {
                return PartialView("_gameDetails", gameDetailsVM);
            }
        }

        [HttpGet]
        public ActionResult CreateNewGame()
        {
            var newGameCreateVM = new GameCreateVM();
            return PartialView("_gameCreate", newGameCreateVM);
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewGame(GameCreateVM newGameCreateVM)
        {
            newGameCreateVM.NewPlayer.Name = newGameCreateVM.Owner;

            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg => { cfg.CreateMap<GameCreateVM, Game>(); });
                IMapper iMapper = config.CreateMapper();
                var newGame = iMapper.Map<GameCreateVM, Game>(newGameCreateVM);

                config = new MapperConfiguration(cfg => { cfg.CreateMap<NewPlayerVM, Player>(); });
                iMapper = config.CreateMapper();
                var newPlayer = iMapper.Map<NewPlayerVM, Player>(newGameCreateVM.NewPlayer);

                newGame.Status = GameStatus.Open;
                newGame.PlayerList.Add(newPlayer);

                var result = await gamesResource.CreateNewGame(newGame);

                if (result.IsSuccessStatusCode)
                {
                    return PartialView("_gameCreateSuccessful");
                }
                else
                {
                    ModelState.AddModelError("CustomError", result.ToString());
                    return PartialView("_gameCreate", newGameCreateVM);
                }
            }
            else
            {
                return PartialView("_gameCreate", newGameCreateVM);
            }
        }

        public async Task<ActionResult> DeleteGame(long id)
        {
            using (var client = HttpClientHelper.GetHttpClient())
            {
                HttpResponseMessage result = await client.DeleteAsync("api/Games/" + id.ToString());

                if (result.IsSuccessStatusCode)
                {
                }

                return RedirectToAction("Index", "Home");
            }
        }
    }
}

RoRService/RoRService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        <section id="global-nav">
            <nav class="navbar">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ror-navbar-collapse" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <input id="loggedInUser" type="hidden" value="@User.Identity.Name" />
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="ror-navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="@Url.Action("Index", "GameLobby")">Game Lobby</a></li>
                            <li><a href="@Url.Action("Index", "GameBoard")">Game Board</a></li>
                            @*<li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>*@
                        </ul>
                    @Html.Partial("_LoginPartial")
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </section>
    </header>


    <div class="body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/ror-initialise.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

RoRService/RoRService/Views/Shared/_banner.cshtml
<section id="rorBanner" class="banner">
    <div class="banner-heading text-title augustus">
        THE REPUBLIC OF ROME
    </div>
    <div class="banner-text text-sub-heading">
        A web based version of the classic Avalon Hill board game.
    </div>
</section>